name: app_locker360
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0-235.0.dev

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Background & Native
  flutter_background_service: ^5.0.0
  device_apps: ^2.2.0
  usage_stats: ^1.2.0

  # UI Tools
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Encryption & File Management
  encrypt: ^5.0.3
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  video_thumbnail: ^0.5.3
  image: ^4.0.17
  photo_manager: ^3.0.0

  # File Preview
  photo_view: ^0.14.0
  video_player: ^2.8.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
